# Generated by Django 5.2.8 on 2025-12-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=30)),
                ('tipo_tela', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('stock', models.CharField(max_length=100)),
                ('imagen_url', models.CharField(max_length=500)),
            ],
        ),
    ]
